//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [Key, Column(Order =0)]
        [Required(ErrorMessage = "user name is  Required")]
        public string username { get; set; }
        [Required(ErrorMessage = "password is  Required")]
        public string password { get; set; }
        public string type { get; set; }
    }
}
